Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> type(20)
<class 'int'>
>>> type(20.5)
<class 'float'>
>>> type("String")
<class 'str'>
>>> type(4j)
<class 'complex'>
>>> type([1,2,3,4,5])
<class 'list'>
>>> type((1,2,3,4))
<class 'tuple'>
>>> type({1,2,3,4,5})
<class 'set'>
>>> type({"name":"Vishal","Age":18})
<class 'dict'>
>>> type(frozenset({1,2,3,4,5}))
<class 'frozenset'>
>>> type(True)
<class 'bool'>
>>> type(b"Hello")
<class 'bytes'>
>>> type(memoryview(bytes(5)))
<class 'memoryview'>
>>> type(None)
<class 'NoneType'>
>>> type(range(4))
<class 'range'>
